"""Change file_url in Todo to file_path

Revision ID: aaa4491d021b
Revises: 43c36c063ae2
Create Date: 2024-09-11 06:38:02.363143

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aaa4491d021b"
down_revision: Union[str, None] = "43c36c063ae2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "todo",
        sa.Column("file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.drop_column("todo", "file_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "todo", sa.Column("file_url", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("todo", "file_path")
    # ### end Alembic commands ###
