"""Remove file_path and file_name from todo model

Revision ID: bdb95e8b4faf
Revises: aaa4491d021b
Create Date: 2024-09-11 16:19:52.663574

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bdb95e8b4faf"
down_revision: Union[str, None] = "aaa4491d021b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("todo", "file_name")
    op.drop_column("todo", "file_path")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "todo", sa.Column("file_path", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "todo", sa.Column("file_name", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
